//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PartShop.ER
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoughtStuff
    {
        public int Nr { get; set; }
        public double Price { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public int User { get; set; }
    }
}
